### ISSUE TITLE
Why named it "CNN" Model? It doesn't contain any CNN layer actually.

### ISSUE THREAD

**Issue by zhmou** [yliang725/Anomaly-Detection-IoT23#2]
![image](https://user-images.githubusercontent.com/43105172/180675835-63145b77-fb3b-4910-a272-f8fa7a7e2559.png)
As can be seen from the summary, there is no convolutional layer in this model, only Dense layer (you can call it "Fully Connected Layer" otherwise) and Dropout layer. I think it better might be called MLP (MultiLayer Perceptron) model.

**Comment by yliang725** [comment]
You might be right. 
I will leave it as it is right now since I don't have time to maintain this project currently.
Feel free point out the issues of this project so others will know when they use this as referrence.
